source 'https://github.com/CocoaPods/Specs.git'

target 'GAT-Simple-KML', :exclusive => true do
  pod "GAT-Simple-KML", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "GAT-Simple-KML", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
